version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels with statistics"
    columns:
      - name: channel_key
        description: "Surrogate key for channel dimension"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: channel_type
        description: "Classification of channel (Pharmaceutical, Cosmetics, Medical, Other)"
      - name: total_posts
        description: "Total number of posts in the channel"
        tests:
          - not_null
          
  - name: dim_dates
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate key for date dimension"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date"
        tests:
          - not_null
          
  - name: fct_messages
    description: "Fact table for Telegram messages with foreign keys to dimensions"
    columns:
      - name: message_key
        description: "Surrogate key for message"
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null